# This is the production overrides compose file
version: '3.8'
services:
  web:
    image: bandar:latest
    command: sh -c "/wait && bin/rails server --port=3000 --binding='0.0.0.0' --environment=production --early-hints"
    ports:
      - 3000:3000
    volumes:
      - log-data:/triptych/log
    env_file:
      - '.env'
      - '.env.production.local'
    depends_on:
      - postgres
      - redis
  clockwork:
    image: bandar:latest
    command: sh -c "/wait && bin/clockwork config/clockwork.rb"
    volumes:
      - log-data:/triptych/log
    env_file:
      - '.env'
      - '.env.production.local'
    depends_on:
      - postgres
      - redis
  goodjob:
    image: bandar:latest
    command: sh -c "/wait && bin/good_job start"
    volumes:
      - log-data:/triptych/log
    env_file:
      - '.env'
      - '.env.production.local'
    depends_on:
      - postgres
      - redis
  postgres:
    env_file:
      - '.env'
      - '.env.production.local'
  redis:
    env_file:
      - '.env'
      - '.env.production.local'
volumes:
  postgres-data:
  redis-data:
  log-data:
